//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrobblerForKbMediaPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrobblerForKbMediaPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorApp {
            get {
                return ResourceManager.GetString("ErrorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワークの接続失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNetwork {
            get {
                return ResourceManager.GetString("ErrorNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} / {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatNotificationMessage {
            get {
                return ResourceManager.GetString("FormatNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証済です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageAuthenticated {
            get {
                return ResourceManager.GetString("MessageAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageAuthenticatedFailed {
            get {
                return ResourceManager.GetString("MessageAuthenticatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageAuthenticatedNot {
            get {
                return ResourceManager.GetString("MessageAuthenticatedNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザでユーザ認証を行った後、OKボタンを押してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageAuthentication {
            get {
                return ResourceManager.GetString("MessageAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last.fmアカウントの認証を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageAuthorizeFailedText {
            get {
                return ResourceManager.GetString("MessageAuthorizeFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageAuthorizeFailedTitle {
            get {
                return ResourceManager.GetString("MessageAuthorizeFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageConfirmExit {
            get {
                return ResourceManager.GetString("MessageConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   多重起動はできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageMutex {
            get {
                return ResourceManager.GetString("MessageMutex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップにショートカットを作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageStartupCreated {
            get {
                return ResourceManager.GetString("MessageStartupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップからショートカットを削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageStartupDelete {
            get {
                return ResourceManager.GetString("MessageStartupDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップにショートカットが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageStartupNotExists {
            get {
                return ResourceManager.GetString("MessageStartupNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップにショートカットが存在します。
        ///上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageStartupOverwrite {
            get {
                return ResourceManager.GetString("MessageStartupOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loved Tracks に追加しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleNotificationLove {
            get {
                return ResourceManager.GetString("TitleNotificationLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loved Tracks の追加に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleNotificationLoveFailed {
            get {
                return ResourceManager.GetString("TitleNotificationLoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scrobble しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleNotificationScrobble {
            get {
                return ResourceManager.GetString("TitleNotificationScrobble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scrobble に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleNotificationScrobbleFailed {
            get {
                return ResourceManager.GetString("TitleNotificationScrobbleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loved Tracks から削除しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleNotificationUnlove {
            get {
                return ResourceManager.GetString("TitleNotificationUnlove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loved Tracks の削除に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleNotificationUnloveFailed {
            get {
                return ResourceManager.GetString("TitleNotificationUnloveFailed", resourceCulture);
            }
        }
    }
}
